### ISSUE TITLE
Question about the multimodel end point sampling

### ISSUE THREAD

**Issue by JiajianLu** [HarshayuGirase/Human-Path-Prediction#20]
Hi, thank you for providing the code. I'm just wondering how do you sample the multimodel end points from only one Gaussian distribution? Should it be GMM instead?

**Comment by DeepOzean** [comment]
The end point distribution are not Gaussian. They are non-parameterized, i.e., each pixel has a probability value. For goals we use TTST to sample (see paper) and for trajectory points, we use softargmax.
