### ISSUE TITLE
Question about data preprocessing.  How to convert the raw dataset into the picke files?

### ISSUE THREAD

**Issue by kevinlemon** [HarshayuGirase/Human-Path-Prediction#21]
Thank you for sharing your code. It is a wonderful work.
I am wondering how to generate the pickle files that used in this code. 
As far as I know, the raw ETH dataset is provided in the data format something like this "  [frame number, pedestrain ID, y, x]
Although the dataset processing script is provided (https://drive.google.com/drive/folders/1ee9h_WtoXZhXZPT0H55uDFZaSmoArbf0?usp=sharing), the pre-processing script is not given.
Could your share your work on how to convert the raw dataset into the picke files? 
Thank you very much!

**Comment by HarshayuGirase** [comment]
Hi,

The pre-processing script for ETH/UCY is not provided in the given link, but we used similar processing as done for SDD: [https://github.com/HarshayuGirase/PECNet/blob/master/utils/social_utils.py#L92]. Here you can see how the raw data format is processed. If I find the pre-processing script for ETH/UCY I will upload it here. Hope this helps!

**Comment by godspeed5** [comment]
I have the same issue for the inD dataset. Can the preprocessing script be provided?

**Comment by HarshayuGirase** [comment]
Hi,

Sorry for the delayed response. The script has been added: https://github.com/HarshayuGirase/Human-Path-Prediction/blob/master/ynet/utils/preprocessing_inD.py

Thanks!
