### ISSUE TITLE
Config of the ETH-UCY

### ISSUE THREAD

**Issue by os1a** [HarshayuGirase/Human-Path-Prediction#22]
Hi,

Thanks for sharing the code of your great work.

Could you please share the optimal config file of the ETH-UCY. If I use a similar config file as the SDD, I am getting a lot worse results (errors are almost twice larger).

I used the same training script and pickle files provided for ETH-UCY. 

Or even better, if you can share with us the pretrained model you obtain for ETH-UCY, so we can reproduce the results on this dataset.

Best,
Osama

**Comment by amitsunde** [comment]
I have same question. Can you provide optimal config file of the ETH-UCY?

**Comment by HarshayuGirase** [comment]
Hi,

Unfortunately, we don’t have the **exact** config parameters we used. However, we were able to reproduce results and have provided notebooks to reproduce experiments for PECNET without pooling/TT (https://drive.google.com/drive/folders/1WtPEdV2aVl8ASZAk5h7fyZpa5xiRDTyv). Please see: https://github.com/HarshayuGirase/PECNet/issues/7 for more details. The main parameter to change would be data_scale. I believe the value may depend on the scene, but somewhere between 150-190 should work.

**Comment by Sdabuliu** [comment]
I have the same questions, can not reproduce the results on ETH/UCY,(errors are almost twice lager) I didn't change the pickle. 

> Hi,
> 
> Thanks for sharing the code of your great work.
> 
> Could you please share the optimal config file of the ETH-UCY. If I use a similar config file as the SDD, I am getting a lot worse results (errors are almost twice larger).
> 
> I used the same training script and pickle files provided for ETH-UCY.
> 
> Or even better, if you can share with us the pretrained model you obtain for ETH-UCY, so we can reproduce the results on this dataset.
> 
> Best, Osama



> Hi,
> 
> Thanks for sharing the code of your great work.
> 
> Could you please share the optimal config file of the ETH-UCY. If I use a similar config file as the SDD, I am getting a lot worse results (errors are almost twice larger).
> 
> I used the same training script and pickle files provided for ETH-UCY.
> 
> Or even better, if you can share with us the pretrained model you obtain for ETH-UCY, so we can reproduce the results on this dataset.
> 
> Best, Osama

Have you soled the problem? I have the same question, error are almost twice lager

**Comment by Arphry** [comment]
> Hi,
> 
> Thanks for sharing the code of your great work.
> 
> Could you please share the optimal config file of the ETH-UCY. If I use a similar config file as the SDD, I am getting a lot worse results (errors are almost twice larger).
> 
> I used the same training script and pickle files provided for ETH-UCY.
> 
> Or even better, if you can share with us the pretrained model you obtain for ETH-UCY, so we can reproduce the results on this dataset. 
> 
> Best, Osama
Have you get the results reported in the paper? I have the same question,error are twice lager.
