### ISSUE TITLE
Conceptual Understanding 

### ISSUE THREAD

**Issue by TeingQiHao** [HarshayuGirase/Human-Path-Prediction#30]
Hi all,

I wish to use this model to predict trajectories of all objects (static and dynamic) captured by my camera. And my camera is moving as well. Can this model be used in such a case to get trajectories of the objects? Thank you.

**Comment by DeepOzean** [comment]
Theoretically yes, assuming you have an object detector that outputs the pixel coordinates of the objects. The setting is quite different, 1) Your view is ego-view, 2) the camera is moving. So you would need to retrain a new model on this setting. It would be great if you can share your experience how the model performs in this setting :)

**Comment by TeingQiHao** [comment]
Thank you for your inputs. I will try to train a new model for moving camera and update you on it.
