### ISSUE TITLE
Trajectory Heatmaps for ETH/UCY

### ISSUE THREAD

**Issue by benedettaliberatori** [HarshayuGirase/Human-Path-Prediction#31]
Hi, Thank you for your contribution and for providing the code! 
I have a question regarding the trajectory heatmaps computation for the ETH/UCY datsets. 
The `resize` parameter from the config file and the value `4200` set the resolution of the big distance matrix template: 

https://github.com/HarshayuGirase/Human-Path-Prediction/blob/ec6cca5f7f5cd49e6c71ebadc31c05cb8615bbf9/ynet/model.py#L295

Could you kindly provide the values used for these datsets ? 

Many thanks in advance.

**Comment by HarshayuGirase** [comment]
Hi,

The resize value we used is 0.66. Decreasing the resize parameter more can allow for bigger batch size.
